import type { JsxCustomElementAttributes } from '@ecopages/jsx';
import type { RuiAlertProps } from './components/ui/alert/alert.script';
import type { RuiBreadcrumbProps } from './components/ui/breadcrumb/breadcrumb.script';
import type { RuiCarouselProps } from './components/ui/carousel/carousel.script';
import type { RuiCheckboxProps } from './components/ui/checkbox/checkbox.script';
import type { RuiComboboxProps } from './components/ui/combobox/combobox.script';
import type { RuiDialogProps } from './components/ui/dialog/dialog.script';
import type { RuiDisclosureGroupProps } from './components/ui/disclosure/disclosure-group.script';
import type { RuiDisclosureProps } from './components/ui/disclosure/disclosure.script';
import type { RuiFieldProps } from './components/ui/field/field.script';
import type { RuiFeedProps } from './components/ui/feed/feed.script';
import type { RuiFormProps } from './components/ui/form/form.script';
import type { RuiGridProps } from './components/ui/grid/grid.script';
import type { RuiListboxProps } from './components/ui/listbox/listbox.script';
import type { RuiMenuButtonProps } from './components/ui/menu-button/menu-button.script';
import type { RuiMenubarProps } from './components/ui/menubar/menubar.script';
import type { RuiMeterProps } from './components/ui/meter/meter.script';
import type { RuiNavigationMenuProps } from './components/ui/navigation-menu/navigation-menu.script';
import type { RuiRadioGroupProps } from './components/ui/radio-group/radio-group.script';
import type { RuiSidebarProps } from './components/ui/sidebar/sidebar.script';
import type { RuiSidebarTriggerProps } from './components/ui/sidebar/sidebar-trigger.script';
import type { RuiSliderProps } from './components/ui/slider/slider.script';
import type { RuiSpinbuttonProps } from './components/ui/spinbutton/spinbutton.script';
import type { RuiSwitchProps } from './components/ui/switch/switch.script';
import type { RuiTabsProps } from './components/ui/tabs/tabs.script';
import type { RuiToolbarProps } from './components/ui/toolbar/toolbar.script';
import type { RuiToastProps } from './components/ui/toast/toast.script';
import type { RuiToasterProps } from './components/ui/toast/toaster.script';
import type { RuiTooltipProps } from './components/ui/tooltip/tooltip.script';
import type { RuiTreeProps } from './components/ui/tree/tree.script';
import type { RuiTreegridProps } from './components/ui/treegrid/treegrid.script';
import type { RuiWindowSplitterProps } from './components/ui/window-splitter/window-splitter.script';

declare module '@ecopages/jsx/jsx-runtime' {
	interface JsxCustomIntrinsicElements {
		'rui-alert': JsxCustomElementAttributes<HTMLElement, RuiAlertProps>;
		'rui-breadcrumb': JsxCustomElementAttributes<HTMLElement, RuiBreadcrumbProps>;
		'rui-carousel': JsxCustomElementAttributes<HTMLElement, RuiCarouselProps>;
		'rui-checkbox': JsxCustomElementAttributes<HTMLElement, RuiCheckboxProps>;
		'rui-combobox': JsxCustomElementAttributes<HTMLElement, RuiComboboxProps>;
		'rui-dialog': JsxCustomElementAttributes<HTMLElement, RuiDialogProps>;
		'rui-disclosure': JsxCustomElementAttributes<HTMLElement, RuiDisclosureProps>;
		'rui-disclosure-group': JsxCustomElementAttributes<HTMLElement, RuiDisclosureGroupProps>;
		'rui-feed': JsxCustomElementAttributes<HTMLElement, RuiFeedProps>;
		'rui-field': JsxCustomElementAttributes<HTMLElement, RuiFieldProps>;
		'rui-form': JsxCustomElementAttributes<HTMLElement, RuiFormProps>;
		'rui-grid': JsxCustomElementAttributes<HTMLElement, RuiGridProps>;
		'rui-listbox': JsxCustomElementAttributes<HTMLElement, RuiListboxProps>;
		'rui-menu-button': JsxCustomElementAttributes<HTMLElement, RuiMenuButtonProps>;
		'rui-menubar': JsxCustomElementAttributes<HTMLElement, RuiMenubarProps>;
		'rui-meter': JsxCustomElementAttributes<HTMLElement, RuiMeterProps>;
		'rui-navigation-menu': JsxCustomElementAttributes<HTMLElement, RuiNavigationMenuProps>;
		'rui-radio-group': JsxCustomElementAttributes<HTMLElement, RuiRadioGroupProps>;
		'rui-sidebar': JsxCustomElementAttributes<HTMLElement, RuiSidebarProps>;
		'rui-sidebar-trigger': JsxCustomElementAttributes<HTMLElement, RuiSidebarTriggerProps>;
		'rui-slider': JsxCustomElementAttributes<HTMLElement, RuiSliderProps>;
		'rui-spinbutton': JsxCustomElementAttributes<HTMLElement, RuiSpinbuttonProps>;
		'rui-switch': JsxCustomElementAttributes<HTMLElement, RuiSwitchProps>;
		'rui-tabs': JsxCustomElementAttributes<HTMLElement, RuiTabsProps>;
		'rui-toast': JsxCustomElementAttributes<HTMLElement, RuiToastProps>;
		'rui-toaster': JsxCustomElementAttributes<HTMLElement, RuiToasterProps>;
		'rui-toolbar': JsxCustomElementAttributes<HTMLElement, RuiToolbarProps>;
		'rui-tooltip': JsxCustomElementAttributes<HTMLElement, RuiTooltipProps>;
		'rui-tree': JsxCustomElementAttributes<HTMLElement, RuiTreeProps>;
		'rui-treegrid': JsxCustomElementAttributes<HTMLElement, RuiTreegridProps>;
		'rui-window-splitter': JsxCustomElementAttributes<HTMLElement, RuiWindowSplitterProps>;
	}
}

export {};
