import type { JsxCustomElementAttributes } from '@ecopages/jsx';
import type { RuiAlert, RuiAlertProps } from './components/ui/alert/alert.script';
import type { RuiBreadcrumb, RuiBreadcrumbProps } from './components/ui/breadcrumb/breadcrumb.script';
import type { RuiCarousel, RuiCarouselProps } from './components/ui/carousel/carousel.script';
import type { RuiCheckbox, RuiCheckboxProps } from './components/ui/checkbox/checkbox.script';
import type { RuiCombobox, RuiComboboxProps } from './components/ui/combobox/combobox.script';
import type { RuiDialog, RuiDialogProps } from './components/ui/dialog/dialog.script';
import type { RuiDisclosureGroup, RuiDisclosureGroupProps } from './components/ui/disclosure/disclosure-group.script';
import type { RuiDisclosure, RuiDisclosureProps } from './components/ui/disclosure/disclosure.script';
import type { RuiField, RuiFieldProps } from './components/ui/field/field.script';
import type { RuiFeed, RuiFeedProps } from './components/ui/feed/feed.script';
import type { RuiForm, RuiFormProps } from './components/ui/form/form.script';
import type { RuiGrid, RuiGridProps } from './components/ui/grid/grid.script';
import type { RuiListbox, RuiListboxProps } from './components/ui/listbox/listbox.script';
import type { RuiMenuButton, RuiMenuButtonProps } from './components/ui/menu-button/menu-button.script';
import type { RuiMenubar, RuiMenubarProps } from './components/ui/menubar/menubar.script';
import type { RuiMeter, RuiMeterProps } from './components/ui/meter/meter.script';
import type { RuiNavigationMenu, RuiNavigationMenuProps } from './components/ui/navigation-menu/navigation-menu.script';
import type { RuiRadioGroup, RuiRadioGroupProps } from './components/ui/radio-group/radio-group.script';
import type { RuiSidebar, RuiSidebarProps } from './components/ui/sidebar/sidebar.script';
import type { RuiSidebarTrigger, RuiSidebarTriggerProps } from './components/ui/sidebar/sidebar-trigger.script';
import type { RuiSlider, RuiSliderProps } from './components/ui/slider/slider.script';
import type { RuiSpinbutton, RuiSpinbuttonProps } from './components/ui/spinbutton/spinbutton.script';
import type { RuiSwitch, RuiSwitchProps } from './components/ui/switch/switch.script';
import type { RuiTabs, RuiTabsProps } from './components/ui/tabs/tabs.script';
import type { RuiToolbar, RuiToolbarProps } from './components/ui/toolbar/toolbar.script';
import type { RuiToast, RuiToastProps } from './components/ui/toast/toast.script';
import type { RuiToaster, RuiToasterProps } from './components/ui/toast/toaster.script';
import type { RuiTooltip, RuiTooltipProps } from './components/ui/tooltip/tooltip.script';
import type { RuiTree, RuiTreeProps } from './components/ui/tree/tree.script';
import type { RuiTreegrid, RuiTreegridProps } from './components/ui/treegrid/treegrid.script';
import type { RuiWindowSplitter, RuiWindowSplitterProps } from './components/ui/window-splitter/window-splitter.script';

declare module '@ecopages/jsx/jsx-runtime' {
	interface JsxCustomIntrinsicElements {
		'rui-alert': JsxCustomElementAttributes<RuiAlert, RuiAlertProps>;
		'rui-breadcrumb': JsxCustomElementAttributes<RuiBreadcrumb, RuiBreadcrumbProps>;
		'rui-carousel': JsxCustomElementAttributes<RuiCarousel, RuiCarouselProps>;
		'rui-checkbox': JsxCustomElementAttributes<RuiCheckbox, RuiCheckboxProps>;
		'rui-combobox': JsxCustomElementAttributes<RuiCombobox, RuiComboboxProps>;
		'rui-dialog': JsxCustomElementAttributes<RuiDialog, RuiDialogProps>;
		'rui-disclosure': JsxCustomElementAttributes<RuiDisclosure, RuiDisclosureProps>;
		'rui-disclosure-group': JsxCustomElementAttributes<RuiDisclosureGroup, RuiDisclosureGroupProps>;
		'rui-feed': JsxCustomElementAttributes<RuiFeed, RuiFeedProps>;
		'rui-field': JsxCustomElementAttributes<RuiField, RuiFieldProps>;
		'rui-form': JsxCustomElementAttributes<RuiForm, RuiFormProps>;
		'rui-grid': JsxCustomElementAttributes<RuiGrid, RuiGridProps>;
		'rui-listbox': JsxCustomElementAttributes<RuiListbox, RuiListboxProps>;
		'rui-menu-button': JsxCustomElementAttributes<RuiMenuButton, RuiMenuButtonProps>;
		'rui-menubar': JsxCustomElementAttributes<RuiMenubar, RuiMenubarProps>;
		'rui-meter': JsxCustomElementAttributes<RuiMeter, RuiMeterProps>;
		'rui-navigation-menu': JsxCustomElementAttributes<RuiNavigationMenu, RuiNavigationMenuProps>;
		'rui-radio-group': JsxCustomElementAttributes<RuiRadioGroup, RuiRadioGroupProps>;
		'rui-sidebar': JsxCustomElementAttributes<RuiSidebar, RuiSidebarProps>;
		'rui-sidebar-trigger': JsxCustomElementAttributes<RuiSidebarTrigger, RuiSidebarTriggerProps>;
		'rui-slider': JsxCustomElementAttributes<RuiSlider, RuiSliderProps>;
		'rui-spinbutton': JsxCustomElementAttributes<RuiSpinbutton, RuiSpinbuttonProps>;
		'rui-switch': JsxCustomElementAttributes<RuiSwitch, RuiSwitchProps>;
		'rui-tabs': JsxCustomElementAttributes<RuiTabs, RuiTabsProps>;
		'rui-toast': JsxCustomElementAttributes<RuiToast, RuiToastProps>;
		'rui-toaster': JsxCustomElementAttributes<RuiToaster, RuiToasterProps>;
		'rui-toolbar': JsxCustomElementAttributes<RuiToolbar, RuiToolbarProps>;
		'rui-tooltip': JsxCustomElementAttributes<RuiTooltip, RuiTooltipProps>;
		'rui-tree': JsxCustomElementAttributes<RuiTree, RuiTreeProps>;
		'rui-treegrid': JsxCustomElementAttributes<RuiTreegrid, RuiTreegridProps>;
		'rui-window-splitter': JsxCustomElementAttributes<RuiWindowSplitter, RuiWindowSplitterProps>;
	}
}

export {};
