/**
 * Generates the `exports` map in package.json and the `src/index.ts` barrel
 * from the component directories found in `src/components/ui`.
 *
 * Convention: every directory inside `src/components/ui` that contains an
 * `index.ts` is a publishable component. Stylesheet exports will be added
 * when CSS bundling lands (separate effort).
 *
 * Run with: bun run generate:exports
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dir, '..');
const UI_DIR = path.join(ROOT, 'src', 'components', 'ui');
const PACKAGE_JSON_PATH = path.join(ROOT, 'package.json');
const BARREL_PATH = path.join(ROOT, 'src', 'index.ts');

type PackageJson = Record<string, unknown> & { exports?: Record<string, unknown> };

function listComponents(): string[] {
	return readdirSync(UI_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory() && existsSync(path.join(UI_DIR, entry.name, 'index.ts')))
		.map((entry) => entry.name)
		.sort();
}

function buildExportsMap(components: string[]): Record<string, unknown> {
	const exports: Record<string, unknown> = {
		'./package.json': './package.json',
		'.': {
			types: './dist/index.d.ts',
			import: './dist/index.js',
		},
	};

	for (const name of components) {
		exports[`./${name}`] = {
			types: `./dist/components/ui/${name}/index.d.ts`,
			import: `./dist/components/ui/${name}/index.js`,
		};
	}

	return exports;
}

function buildBarrel(components: string[]): string {
	const lines = components.map((name) => `export * from './components/ui/${name}';`);
	return `/**\n * Generated by scripts/generate-exports.ts — do not edit by hand.\n * Importing the root entry registers every radiant-ui custom element.\n */\n${lines.join('\n')}\n`;
}

const components = listComponents();

if (components.length === 0) {
	console.error('[generate-exports] no components found in src/components/ui');
	process.exit(1);
}

const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8')) as PackageJson;
packageJson.exports = buildExportsMap(components);
writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(packageJson, null, 2)}\n`);

writeFileSync(BARREL_PATH, buildBarrel(components));

console.log(`[generate-exports] ${components.length} components: ${components.join(', ')}`);
