/**
 * Generates the `exports` map in package.json, the root barrel, and
 * `src/styles/styles.css` (all component CSS, no theme).
 *
 * Run with: bun run generate:exports
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const UI_DIR = path.join(ROOT, 'src', 'components', 'ui');
const PACKAGE_JSON_PATH = path.join(ROOT, 'package.json');
const BARREL_PATH = path.join(ROOT, 'src', 'index.ts');
const STYLES_CSS_PATH = path.join(ROOT, 'src', 'styles', 'styles.css');

type PackageJson = Record<string, unknown> & { exports?: Record<string, unknown> };

function listComponents(): string[] {
	return readdirSync(UI_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory() && existsSync(path.join(UI_DIR, entry.name, 'index.ts')))
		.map((entry) => entry.name)
		.sort();
}

function cssExport(relativeDistPath: string): { default: string } {
	return { default: `./dist/styles/${relativeDistPath}` };
}

function componentCssExport(name: string): { default: string } {
	return { default: `./dist/components/ui/${name}/${name}.css` };
}

function buildStaticStyleExports(): Record<string, { default: string }> {
	const tokenPaths = [
		'tokens/colors/aurora.css',
		'tokens/colors/glacier.css',
		'tokens/colors/basalt.css',
		'tokens/colors/palettes.css',
		'tokens/spacing/compact.css',
		'tokens/spacing/default.css',
		'tokens/spacing/wide.css',
		'tokens/radius/edgy.css',
		'tokens/radius/sharp.css',
		'tokens/radius/default.css',
		'tokens/radius/soft.css',
		'tokens/elevation/default.css',
		'tokens/elevation/flat.css',
		'tokens/typography/default.css',
		'tokens/motion/default.css',
		'tokens/motion/snappy.css',
		'tokens/system.css',
		'tokens/semantic.css',
		'themes/default.css',
		'themes/glacier.css',
		'themes/aurora.css',
		'themes/default-compact-soft.css',
		'styles.css',
		'radiant-ui.css',
		'radiant-ui-core.css',
	];

	const exports: Record<string, { default: string }> = {};
	for (const file of tokenPaths) {
		const subpath = file.replace(/\.css$/, '').replace(/\//g, '/');
		const key =
			file === 'styles.css'
				? './styles.css'
				: file === 'radiant-ui.css'
					? './radiant-ui.css'
					: file === 'radiant-ui-core.css'
						? './radiant-ui-core.css'
						: `./${file.replace(/\.css$/, '')}`;
		exports[key] = cssExport(file);
	}
	return exports;
}

function buildExportsMap(components: string[]): Record<string, unknown> {
	const exports: Record<string, unknown> = {
		'./package.json': './package.json',
		'.': {
			types: './dist/index.d.ts',
			import: './dist/index.js',
		},
		...buildStaticStyleExports(),
	};

	for (const name of components) {
		exports[`./${name}`] = {
			types: `./dist/components/ui/${name}/index.d.ts`,
			import: `./dist/components/ui/${name}/index.js`,
		};
		if (existsSync(path.join(UI_DIR, name, `${name}.css`))) {
			exports[`./${name}/styles.css`] = componentCssExport(name);
		}
	}

	return exports;
}

function buildBarrel(components: string[]): string {
	const lines = components.map((name) => `export * from './components/ui/${name}';`);
	return `/**\n * Generated by scripts/generate-exports.ts — do not edit by hand.\n * Importing the root entry registers every radiant-ui custom element.\n */\n${lines.join('\n')}\n`;
}

function buildStylesEntry(components: string[]): string {
	const imports = [
		'/**',
		' * All component styles (no theme). Import `@ecopages/radiant-ui/themes/default` separately.',
		' * Generated by scripts/generate-exports.ts — do not edit by hand.',
		' */',
		"@import './components/button.css';",
		...components
			.filter((name) => existsSync(path.join(UI_DIR, name, `${name}.css`)))
			.map((name) => `@import '../components/ui/${name}/${name}.css';`),
		'',
	];
	return imports.join('\n');
}

const components = listComponents();

if (components.length === 0) {
	console.error('[generate-exports] no components found in src/components/ui');
	process.exit(1);
}

const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8')) as PackageJson;
packageJson.exports = buildExportsMap(components);
writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(packageJson, null, 2)}\n`);

writeFileSync(BARREL_PATH, buildBarrel(components));
writeFileSync(STYLES_CSS_PATH, buildStylesEntry(components));

console.log(`[generate-exports] ${components.length} components: ${components.join(', ')}`);
