/**
 * Generates the `exports` map in package.json, the root barrel, and
 * `src/styles/styles.css` (all component CSS, no theme).
 *
 * Run with: bun run generate:exports
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
	componentCssDistPath,
	componentCssExportKey,
	isOptionalComponentSkin,
	listComponentCssFiles,
} from './component-style-files.ts';

const ROOT = path.resolve(import.meta.dirname, '..');
const UI_DIR = path.join(ROOT, 'src', 'components', 'ui');
const PACKAGE_JSON_PATH = path.join(ROOT, 'package.json');
const BARREL_PATH = path.join(ROOT, 'src', 'index.ts');
const STYLES_CSS_PATH = path.join(ROOT, 'src', 'styles', 'styles.css');
const STYLE_DEPENDENCIES_PATH = path.join(ROOT, 'src', 'styles', 'style-dependencies.json');
const COMPONENT_IMPORT_PATTERN = /import\s+(?:type\s+)?\{([\s\S]*?)\}\s+from\s+'(\.\.\/[^']+)'/g;
const PRIMITIVE_STYLE_PATTERN = /rui-(?:control-toggle|popover|floating|icon)|<RuiIcon[A-Z]/;
const CLASS_STYLE_DEPENDENCIES = [{ pattern: /rui-button/, component: 'button' }];

type PackageJson = Record<string, unknown> & { exports?: Record<string, unknown> };
type StyleDependencyManifest = Record<string, { direct: string[]; styles: string[] }>;

function listComponents(): string[] {
	return readdirSync(UI_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory() && existsSync(path.join(UI_DIR, entry.name, 'index.ts')))
		.map((entry) => entry.name)
		.sort();
}

function cssExport(relativeDistPath: string): { default: string } {
	return { default: `./dist/styles/${relativeDistPath}` };
}

function componentCssExport(name: string, filename: string): { default: string } {
	return { default: componentCssDistPath(name, filename) };
}

function buildComponentStyleExports(name: string): Record<string, { default: string }> {
	const dir = path.join(UI_DIR, name);
	const exports: Record<string, { default: string }> = {};

	for (const filename of listComponentCssFiles(dir)) {
		exports[componentCssExportKey(name, filename)] = componentCssExport(name, filename);
	}

	return exports;
}

function buildStaticStyleExports(): Record<string, { default: string }> {
	const tokenPaths = [
		'tokens/colors/aurora.css',
		'tokens/colors/glacier.css',
		'tokens/colors/basalt.css',
		'tokens/colors/palettes.css',
		'tokens/spacing/compact.css',
		'tokens/spacing/default.css',
		'tokens/spacing/wide.css',
		'tokens/radius/edgy.css',
		'tokens/radius/sharp.css',
		'tokens/radius/default.css',
		'tokens/radius/soft.css',
		'tokens/elevation/default.css',
		'tokens/elevation/flat.css',
		'tokens/typography/default.css',
		'tokens/motion/default.css',
		'tokens/motion/snappy.css',
		'tokens/system.css',
		'tokens/semantic.css',
		'themes/default.css',
		'themes/glacier.css',
		'themes/aurora.css',
		'themes/default-compact-soft.css',
		'styles.css',
		'primitives.css',
		'radiant-ui.css',
		'radiant-ui-core.css',
	];

	const exports: Record<string, { default: string }> = {};
	for (const file of tokenPaths) {
		const key =
			file === 'styles.css'
				? './styles.css'
				: file === 'primitives.css'
					? './primitives.css'
				: file === 'radiant-ui.css'
					? './radiant-ui.css'
					: file === 'radiant-ui-core.css'
						? './radiant-ui-core.css'
						: `./${file.replace(/\.css$/, '')}`;
		exports[key] = cssExport(file);
	}
	exports['./style-dependencies'] = { default: './dist/styles/style-dependencies.json' };
	return exports;
}

function buildExportsMap(components: string[]): Record<string, unknown> {
	const exports: Record<string, unknown> = {
		'./package.json': './package.json',
		'.': {
			types: './dist/index.d.ts',
			import: './dist/index.js',
		},
		'./cx': {
			types: './dist/cx.d.ts',
			import: './dist/cx.js',
		},
		'./aria': {
			types: './dist/aria.d.ts',
			import: './dist/aria.js',
		},
		...buildStaticStyleExports(),
	};

	for (const name of components) {
		exports[`./${name}`] = {
			types: `./dist/components/ui/${name}/index.d.ts`,
			import: `./dist/components/ui/${name}/index.js`,
		};
		Object.assign(exports, buildComponentStyleExports(name));
	}

	return exports;
}

function buildBarrel(components: string[]): string {
	const lines = components.map((name) => `export * from './components/ui/${name}';`);
	return `/**\n * Generated by scripts/generate-exports.ts — do not edit by hand.\n * Importing the root entry registers every radiant-ui custom element.\n */\nexport { withDefaultAriaLabel } from './aria';\nexport { cx } from './lib/cx';\n${lines.join('\n')}\n`;
}

function buildStylesEntry(components: string[]): string {
	const imports = [
		'/**',
		' * All component styles (no theme). Import `@ecopages/radiant-ui/themes/default` separately.',
		' * Generated by scripts/generate-exports.ts — do not edit by hand.',
		' */',
		"@import './primitives.css';",
		...components.flatMap((name) => {
			const dir = path.join(UI_DIR, name);
			return listComponentCssFiles(dir)
				.filter((filename) => !isOptionalComponentSkin(name, filename))
				.map((filename) => `@import '../components/ui/${name}/${filename}';`);
		}),
		'',
	];
	return imports.join('\n');
}

function renderedComponentName(bindings: string, viewSource: string): string | undefined {
	const componentNames = bindings.match(/\bRui[A-Z]\w*/g) ?? [];
	return componentNames.find((componentName) => new RegExp(`<${componentName}(?:\\s|/|>)`).test(viewSource));
}

function componentNameFromImport(importPath: string): string {
	return importPath.slice(3).split('/')[0];
}

function directStyleDependencies(component: string, components: Set<string>): string[] {
	const viewPath = path.join(UI_DIR, component, `${component}.tsx`);
	if (!existsSync(viewPath)) {
		return [];
	}

	const viewSource = readFileSync(viewPath, 'utf8');
	const dependencies = new Set<string>();
	for (const match of viewSource.matchAll(COMPONENT_IMPORT_PATTERN)) {
		const [, bindings, importPath] = match;
		const dependency = componentNameFromImport(importPath);
		if (dependency !== component && components.has(dependency) && renderedComponentName(bindings, viewSource)) {
			dependencies.add(dependency);
		}
	}

	if (PRIMITIVE_STYLE_PATTERN.test(viewSource)) {
		dependencies.add('primitives');
	}
	for (const dependency of CLASS_STYLE_DEPENDENCIES) {
		if (dependency.component !== component && dependency.pattern.test(viewSource)) {
			dependencies.add(dependency.component);
		}
	}

	return [...dependencies].sort();
}

function styleSpecifier(component: string): string {
	return component === 'primitives'
		? '@ecopages/radiant-ui/primitives.css'
		: `@ecopages/radiant-ui/${component}/styles.css`;
}

function buildStyleDependencyManifest(components: string[]): StyleDependencyManifest {
	const componentSet = new Set(components);
	const direct = new Map(components.map((component) => [component, directStyleDependencies(component, componentSet)]));

	function resolve(component: string, seen = new Set<string>()): string[] {
		if (seen.has(component)) {
			return [];
		}
		seen.add(component);

		const resolved: string[] = [];
		for (const dependency of direct.get(component) ?? []) {
			if (dependency !== 'primitives') {
				resolved.push(...resolve(dependency, seen));
			}
			resolved.push(dependency);
		}
		return [...new Set(resolved)];
	}

	return Object.fromEntries(
		components.map((component) => {
			const dependencies = resolve(component);
			return [component, { direct: direct.get(component) ?? [], styles: [...dependencies, component].map(styleSpecifier) }];
		}),
	);
}

const components = listComponents();

if (components.length === 0) {
	console.error('[generate-exports] no components found in src/components/ui');
	process.exit(1);
}

const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8')) as PackageJson;
packageJson.exports = buildExportsMap(components);
/* Tabs, matching the repo's Prettier config — two spaces reformatted all ~490 lines on
   every build, so each release commit carried a whole-file whitespace diff. */
writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(packageJson, null, '\t')}\n`);

writeFileSync(BARREL_PATH, buildBarrel(components));
writeFileSync(STYLES_CSS_PATH, buildStylesEntry(components));
writeFileSync(
	STYLE_DEPENDENCIES_PATH,
	`${JSON.stringify({ components: buildStyleDependencyManifest(components) }, null, '\t')}\n`,
);

console.log(`[generate-exports] ${components.length} components: ${components.join(', ')}`);
