import {
	RadiantElement,
	bindTo,
	customElement,
	event,
	onEvent,
	onUpdated,
	prop,
	registerSsrPreparationCallback,
	state,
} from '@ecopages/radiant';
import type { EventEmitter } from '@ecopages/radiant/tools/event-emitter';
import { dateToIso, isoToDate, isIsoInRange } from '@/lib/intl-date';
import {
	allSegmentsEmpty,
	applyBackspaceToSegment,
	applyDigitToSegment,
	buildDateSegments,
	firstEmptyOrFirstPart,
	focusPartAfter,
	incrementSegmentValue,
	segmentDisplayText,
	segmentsToDate,
	type DatePartType,
	type DateSegmentModel,
} from '@/lib/intl-date';
import { resolveLocale } from '@/lib/intl/locale';
import { uniqueId } from '@/lib/unique-id';
import { getSegmentDomProps } from './date-input-segment-dom';

export type RuiDateInputProps = {
	value?: string;
	min?: string;
	max?: string;
	disabled?: boolean;
	readOnly?: boolean;
	name?: string;
	label?: string;
	locale?: string;
};

export type RuiDateInputChangeDetail = { value: string };

function isIosDevice(): boolean {
	if (typeof navigator === 'undefined') {
		return false;
	}
	return /iPad|iPhone|iPod/.test(navigator.userAgent);
}

/**
 * `<rui-date-input>` — locale-ordered date segments for keyboard and touch entry.
 *
 * Derived Tree: the host `render()` paints editable segments and a hidden ISO input.
 *
 * ## Light-DOM contract
 *
 * Generated by `render()` (do not author manually):
 * - `[data-ref="root"]` — segment group (`role="group"`). Host sets `id` when labelled.
 * - `[data-date-segment][data-type="month|day|year"]` — editable units (`contenteditable`).
 * - `[data-date-input-hidden]` — hidden form value (`YYYY-MM-DD`).
 *
 * @see https://react-aria.adobe.com/DateField
 * @element rui-date-input
 * @attr {string} value - Canonical ISO `YYYY-MM-DD`. Default: `''`.
 * @attr {string} min - Earliest allowed ISO date. Default: `''`.
 * @attr {string} max - Latest allowed ISO date. Default: `''`.
 * @attr {boolean} disabled - Disable editing. Default: `false`.
 * @attr {boolean} read-only - Show value without editing. Default: `false`.
 * @attr {string} name - Form name on the hidden input. Default: `''`.
 * @attr {string} label - Accessible name when there is no associated label. Default: `''`.
 * @attr {string} locale - BCP 47 locale tag, or comma-separated fallback list. Default: `''`.
 * @fires rui-change - Emitted when a complete valid date is committed, or when all segments are cleared.
 *
 * @remarks
 * `segments` is the visible draft. `value` and the hidden input stay on the last
 * committed ISO date until a unit completes, focus moves, or the control blurs.
 * An in-progress digit buffer is not published just because the draft parses as
 * a date. A delayed selection collapse runs only while that segment is still
 * `document.activeElement`.
 */
@customElement('rui-date-input')
export class RuiDateInput extends RadiantElement {
	@prop({ type: String, reflect: true, defaultValue: '' }) value: string;
	@prop({ type: String, defaultValue: '' }) min: string;
	@prop({ type: String, defaultValue: '' }) max: string;

	@prop({ type: Boolean, reflect: true, defaultValue: false })
	@bindTo({ selector: '[data-date-input-hidden]', prop: 'disabled' })
	disabled: boolean;

	@prop({ type: Boolean, attribute: 'read-only', reflect: true, defaultValue: false })
	readOnly: boolean;

	@prop({ type: String, defaultValue: '' })
	@bindTo({ selector: '[data-date-input-hidden]', prop: 'name' })
	name: string;

	@prop({ type: String, defaultValue: '' }) label: string;
	@prop({ type: String, defaultValue: '' }) locale: string;

	@event({ name: 'rui-change', bubbles: true, composed: true })
	changeEvent: EventEmitter<RuiDateInputChangeDetail>;

	@state segments: DateSegmentModel[] = [];
	@state focusedPart: DatePartType | null = null;
	@state hiddenValue = '';

	private readonly uid = uniqueId('rui-date-input');
	private enteredKeys: Partial<Record<DatePartType, string>> = {};
	private useTextboxRole = isIosDevice();
	private pendingFocus: DatePartType | null = null;

	private get resolvedLocale(): string | string[] | undefined {
		return resolveLocale(this.locale);
	}

	private get isoValue(): string {
		return this.value ?? '';
	}

	private syncSegmentsFromValue(): void {
		const date = isoToDate(this.isoValue);
		this.segments = buildDateSegments(date, this.resolvedLocale);
		this.hiddenValue = this.isoValue;
		this.enteredKeys = {};
	}

	/**
	 * @remarks Segment `@state` is filled in `onConnected` / `@onUpdated`, which run
	 * after the first client render and not during SSR. Derive from `value` until synced.
	 */
	private get displaySegments(): DateSegmentModel[] {
		if (this.segments.length > 0) {
			return this.segments;
		}
		return buildDateSegments(isoToDate(this.isoValue), this.resolvedLocale);
	}

	private get displayHiddenValue(): string {
		return this.hiddenValue || this.isoValue;
	}

	constructor() {
		super();
		registerSsrPreparationCallback(this, () => this.syncSegmentsFromValue());
	}

	private getSegmentElement(type: DatePartType): HTMLElement | null {
		return this.querySelector<HTMLElement>(`[data-date-segment][data-type="${type}"]`);
	}

	private focusPart(type: DatePartType | null): void {
		this.leaveEditedPart(type);
		this.focusedPart = type;
		this.pendingFocus = type;
		if (!type) {
			return;
		}
		this.scheduleFocusedSegmentSync(type);
	}

	/**
	 * Restores focus and caret after a render only when this part should still own them.
	 *
	 * @remarks A queued `selection.collapse()` on a segment that is no longer
	 * `focusedPart` would pull focus back (day ↔ year). Ignore `focusin` on the
	 * previous segment until this microtask has moved focus.
	 */
	private scheduleFocusedSegmentSync(type: DatePartType): void {
		queueMicrotask(() => {
			if (this.pendingFocus === type) {
				this.pendingFocus = null;
			}
			const segment = this.getSegmentElement(type);
			if (!segment || this.focusedPart !== type) {
				return;
			}

			if (document.activeElement !== segment) {
				segment.focus();
			}

			if (document.activeElement === segment) {
				window.getSelection()?.collapse(segment, 0);
			}
		});
	}

	private hasInProgressEntry(): boolean {
		const part = this.focusedPart;
		return part != null && Boolean(this.enteredKeys[part]);
	}

	private yearDigitsComplete(): boolean {
		const year = this.segments.find((segment) => segment.editable && segment.type === 'year');
		if (!year || year.isPlaceholder || year.value === '') {
			return true;
		}
		return year.value.replace(/\D/g, '').length >= 4;
	}

	private leaveEditedPart(next: DatePartType | null): void {
		const previous = this.focusedPart;
		if (previous == null || previous === next) {
			return;
		}
		this.enteredKeys[previous] = '';
		if (!this.tryCommit() && !this.yearDigitsComplete()) {
			this.syncSegmentsFromValue();
		}
	}

	private restoreDraftIfInvalid(): void {
		if (allSegmentsEmpty(this.segments)) {
			return;
		}
		if (segmentsToDate(this.segments) && this.yearDigitsComplete()) {
			return;
		}
		this.syncSegmentsFromValue();
	}

	private tryCommit(): boolean {
		if (this.hasInProgressEntry() || !this.yearDigitsComplete()) {
			return false;
		}

		if (allSegmentsEmpty(this.segments)) {
			if (this.isoValue !== '') {
				this.value = '';
				this.hiddenValue = '';
				this.changeEvent.emit({ value: '' });
			}
			return true;
		}

		const date = segmentsToDate(this.segments);
		if (!date) {
			return false;
		}

		const iso = dateToIso(date);
		if (!isIsoInRange(iso, this.min || undefined, this.max || undefined)) {
			this.syncSegmentsFromValue();
			return false;
		}

		if (iso === this.isoValue) {
			this.hiddenValue = iso;
			return true;
		}

		this.value = iso;
		this.hiddenValue = iso;
		this.changeEvent.emit({ value: iso });
		this.syncSegmentsFromValue();
		return true;
	}

	private partFromTarget(target: EventTarget | null): DatePartType | null {
		if (!(target instanceof HTMLElement)) {
			return null;
		}
		const segment = target.closest<HTMLElement>('[data-date-segment]');
		const type = segment?.getAttribute('data-type');
		if (type === 'month' || type === 'day' || type === 'year') {
			return type;
		}
		return null;
	}

	private handleDigit(part: DatePartType, key: string): void {
		this.focusedPart = part;
		const entered = this.enteredKeys[part] ?? '';
		const result = applyDigitToSegment(this.segments, part, key, entered);
		this.segments = result.segments;
		this.enteredKeys[part] = result.enteredKeys;
		this.tryCommit();
		if (result.focusNext) {
			this.focusPart(focusPartAfter(this.segments, part, 1));
			return;
		}
		this.scheduleFocusedSegmentSync(part);
	}

	private handleBackspace(part: DatePartType): void {
		this.focusedPart = part;
		const result = applyBackspaceToSegment(this.segments, part);
		if (result.kind === 'focus-previous') {
			this.focusPart(focusPartAfter(this.segments, part, -1));
			return;
		}

		this.segments = result.segments;
		this.enteredKeys[part] = result.enteredKeys;
		this.tryCommit();
		this.scheduleFocusedSegmentSync(part);
	}

	private handleIncrement(part: DatePartType, delta: number): void {
		this.focusedPart = part;
		this.enteredKeys[part] = '';
		this.segments = incrementSegmentValue(this.segments, part, delta);
		this.tryCommit();
		this.scheduleFocusedSegmentSync(part);
	}

	protected override onConnected(): void {
		this.syncSegmentsFromValue();
		this.syncGroupLabel();
	}

	@onUpdated(['value', 'min', 'max', 'locale', 'disabled', 'readOnly', 'label', 'name'])
	onPropsUpdated(): void {
		this.syncSegmentsFromValue();
		this.syncGroupLabel();
	}

	private syncGroupLabel(): void {
		const root = this.querySelector<HTMLElement>('[data-ref="root"]');
		if (!root) {
			return;
		}
		if (!root.id) {
			root.id = `${this.uid}-group`;
		}
		const ariaLabel = this.label || this.getAttribute('aria-label') || '';
		if (ariaLabel) {
			root.setAttribute('aria-label', ariaLabel);
		} else {
			root.removeAttribute('aria-label');
		}
	}

	@onEvent({ selector: '[data-ref="root"]', type: 'focusin' })
	onGroupFocusIn(event: FocusEvent): void {
		if (this.partFromTarget(event.target)) {
			return;
		}
		this.focusPart(firstEmptyOrFirstPart(this.segments));
	}

	@onEvent({ selector: '[data-date-segment]', type: 'focusin' })
	onSegmentFocusIn(event: FocusEvent): void {
		const part = this.partFromTarget(event.target);
		if (!part) {
			return;
		}
		if (this.pendingFocus && this.pendingFocus !== part) {
			return;
		}
		this.leaveEditedPart(part);
		if (this.focusedPart !== part) {
			this.enteredKeys[part] = '';
		}
		this.focusedPart = part;
		this.scheduleFocusedSegmentSync(part);
	}

	@onEvent({ selector: '[data-date-segment]', type: 'focusout' })
	onSegmentFocusOut(): void {
		queueMicrotask(() => {
			if (this.matches(':focus-within')) {
				return;
			}
			if (this.focusedPart) {
				this.enteredKeys[this.focusedPart] = '';
			}
			this.focusedPart = null;
			if (!this.tryCommit()) {
				this.restoreDraftIfInvalid();
			}
		});
	}

	@onEvent({ selector: '[data-date-segment]', type: 'keydown' })
	onSegmentKeyDown(event: KeyboardEvent): void {
		const part = this.partFromTarget(event.target);
		if (!part || this.disabled || this.readOnly) {
			return;
		}

		if (event.key === 'ArrowLeft') {
			event.preventDefault();
			this.focusPart(focusPartAfter(this.segments, part, -1));
			return;
		}
		if (event.key === 'ArrowRight') {
			event.preventDefault();
			this.focusPart(focusPartAfter(this.segments, part, 1));
			return;
		}
		if (event.key === 'ArrowUp') {
			event.preventDefault();
			this.handleIncrement(part, 1);
			return;
		}
		if (event.key === 'ArrowDown') {
			event.preventDefault();
			this.handleIncrement(part, -1);
			return;
		}
		if (event.key === 'Backspace' || event.key === 'Delete') {
			event.preventDefault();
			event.stopPropagation();
			this.handleBackspace(part);
		}
	}

	@onEvent({ selector: '[data-date-segment]', type: 'beforeinput' })
	onSegmentBeforeInput(event: InputEvent): void {
		const part = this.partFromTarget(event.target);
		if (!part || this.disabled || this.readOnly) {
			return;
		}
		event.preventDefault();

		switch (event.inputType) {
			case 'deleteContentBackward':
			case 'deleteContentForward':
				this.handleBackspace(part);
				break;
			default:
				if (event.data != null) {
					this.handleDigit(part, event.data);
				}
				break;
		}
	}

	@onEvent({ selector: '[data-date-segment]', type: 'pointerdown' })
	onSegmentPointerDown(event: Event): void {
		event.stopPropagation();
	}

	private renderSegment(segment: DateSegmentModel, index: number) {
		if (!segment.editable) {
			return (
				<span key={`literal-${index}`} class="rui-date-input__literal" data-type="literal" aria-hidden="true">
					{segment.value}
				</span>
			);
		}

		const type = segment.type as DatePartType;
		const focused = this.focusedPart === type;
		const dom = getSegmentDomProps(segment, {
			disabled: this.disabled,
			focused,
			locale: this.resolvedLocale,
			readOnly: this.readOnly,
			segments: this.displaySegments,
			useTextboxRole: this.useTextboxRole,
		});

		return (
			<span
				key={type}
				class={dom.className}
				data-date-segment
				data-type={type}
				data-placeholder={segment.isPlaceholder ? 'true' : undefined}
				data-focused={focused ? 'true' : undefined}
				role={dom.ariaRole}
				aria-label={dom.ariaLabel}
				aria-valuemin={dom.ariaValuemin}
				aria-valuemax={dom.ariaValuemax}
				aria-valuenow={dom.ariaValuenow}
				aria-valuetext={dom.ariaValuetext}
				aria-readonly={dom.ariaReadonly}
				contenteditable={dom.contenteditable}
				suppresscontenteditablewarning={dom.suppresscontenteditablewarning}
				spellcheck="false"
				inputmode={dom.inputmode}
				tabindex={dom.tabindex}
			>
				{segmentDisplayText(segment)}
			</span>
		);
	}

	override render() {
		return (
			<div class="rui-date-input" data-ref="root" role="group">
				<div class="rui-date-input__segments">
					{this.displaySegments.map((segment, index) => this.renderSegment(segment, index))}
				</div>
				<input type="hidden" data-date-input-hidden value={this.displayHiddenValue} />
			</div>
		);
	}
}
