import { defineConfig } from 'tsup';

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		'nitro-config': 'src/nitro-config.ts',
		'runtime/index': 'src/runtime/index.ts',
		'ssr/index': 'src/ssr/index.ts',
		'ssr/headers': 'src/ssr/headers.ts',
		'nitro/index': 'src/nitro/index.ts',
		'nitro/ssr-shim-plugin': 'src/nitro/ssr-shim-plugin.ts',
	},
	format: ['esm'],
	dts: false,
	splitting: false,
	sourcemap: true,
	clean: true,
	target: 'node18',
	platform: 'neutral',
	external: [
		'@babel/core',
		'@babel/plugin-proposal-decorators',
		'@ecopages/jsx',
		'@ecopages/jsx/client',
		'@ecopages/jsx/server',
		'@ecopages/radiant',
		'@ecopages/signals',
		'@rolldown/plugin-babel',
		'nitro',
		'nitro/config',
		'nitro/types',
		'rollup',
		'picomatch',
		'vite',
		'virtual:radiant/app-load-mode',
		'virtual:radiant/client-module-registry',
		'virtual:radiant/components',
		'virtual:radiant/dom-module-registry',
		'virtual:radiant/ssr-asset-registry',
		'virtual:radiant/ssr-client-module-registry',
	],
});
